import Foundation

// MARK: - Localization

enum L10n {

    static func tr(_ key: String) -> String {
        let lang = SettingsManager.shared.language
        return translations[lang]?[key] ?? translations[.en]?[key] ?? key
    }

    // MARK: - Translation Tables

    private static let translations: [SettingsManager.Language: [String: String]] = [
        .ko: ko, .en: en, .zh: zh, .ja: ja, .es: es, .de: de, .fr: fr
    ]

    private static let ko: [String: String] = [
        // App Menu
        "menu.app.about":       "Jena Note 정보",
        "menu.app.hide":        "Jena Note 숨기기",
        "menu.app.hideOthers":  "다른 항목 숨기기",
        "menu.app.showAll":     "모두 보기",
        "menu.app.settings":    "설정...",
        "menu.app.quit":        "Jena Note 종료",
        // File Menu
        "menu.file":            "파일",
        "menu.file.new":        "새 문서",
        "menu.file.open":       "열기...",
        "menu.file.recent":     "최근 열었던 항목",
        "menu.file.recent.empty":"최근 항목 없음",
        "menu.file.recent.clear":"목록 지우기",
        "menu.file.save":       "저장",
        "menu.file.saveAs":     "다른 이름으로 저장...",
        "menu.file.revert":     "되돌리기",
        "menu.file.close":      "닫기",
        // Edit Menu
        "menu.edit":            "편집",
        "menu.edit.undo":       "실행 취소",
        "menu.edit.redo":       "다시 실행",
        "menu.edit.cut":        "오려두기",
        "menu.edit.copy":       "복사",
        "menu.edit.paste":      "붙여넣기",
        "menu.edit.pastePlain":  "서식 없이 붙여넣기",
        "menu.edit.selectAll":  "전체 선택",
        "menu.edit.find":       "찾기...",
        // Format Menu
        "menu.format":          "서식",
        "menu.format.bold":     "굵게",
        "menu.format.italic":   "기울임",
        "menu.format.code":     "코드",
        "menu.format.h1":       "제목 1",
        "menu.format.h2":       "제목 2",
        "menu.format.h3":       "제목 3",
        "menu.format.body":     "본문",
        "menu.format.ul":       "목록",
        "menu.format.ol":       "번호 목록",
        "menu.format.quote":    "인용",
        "menu.format.link":     "링크 삽입",
        // Window Menu
        "menu.window":          "윈도우",
        "menu.window.minimize": "최소화",
        "menu.window.zoom":     "확대/축소",
        "menu.window.front":    "모든 창 앞으로",
        // Help Menu
        "menu.help":            "도움말",
        "menu.help.help":       "Jena Note 도움말",
        // Settings
        "settings.title":       "설정",
        "settings.language":    "언어",
        "settings.appearance":  "컬러 모드",
        "appearance.system":    "시스템",
        "appearance.light":     "라이트",
        "appearance.dark":      "다크",
        // Toolbar
        "toolbar.bold":         "굵게",
        "toolbar.italic":       "기울임",
        "toolbar.code":         "코드",
        "toolbar.h1":           "H1",
        "toolbar.h2":           "H2",
        "toolbar.h3":           "H3",
        "toolbar.body":         "본문",
        "toolbar.ul":           "목록",
        "toolbar.ol":           "번호 목록",
        "toolbar.quote":        "인용",
        "toolbar.link":         "링크",
        "toolbar.hr":           "구분선",
        "toolbar.lineSpacing":  "줄 간격",
        // Misc
        "untitled":             "제목 없음",
        "link.title":           "링크 삽입",
        "link.message":         "URL을 입력하세요",
        "link.insert":          "삽입",
        "link.cancel":          "취소",
    ]

    private static let en: [String: String] = [
        "menu.app.about":       "About Jena Note",
        "menu.app.hide":        "Hide Jena Note",
        "menu.app.hideOthers":  "Hide Others",
        "menu.app.showAll":     "Show All",
        "menu.app.settings":    "Settings...",
        "menu.app.quit":        "Quit Jena Note",
        "menu.file":            "File",
        "menu.file.new":        "New Document",
        "menu.file.open":       "Open...",
        "menu.file.recent":     "Open Recent",
        "menu.file.recent.empty":"No Recent Items",
        "menu.file.recent.clear":"Clear List",
        "menu.file.save":       "Save",
        "menu.file.saveAs":     "Save As...",
        "menu.file.revert":     "Revert to Saved",
        "menu.file.close":      "Close",
        "menu.edit":            "Edit",
        "menu.edit.undo":       "Undo",
        "menu.edit.redo":       "Redo",
        "menu.edit.cut":        "Cut",
        "menu.edit.copy":       "Copy",
        "menu.edit.paste":      "Paste",
        "menu.edit.pastePlain":  "Paste and Match Style",
        "menu.edit.selectAll":  "Select All",
        "menu.edit.find":       "Find...",
        "menu.format":          "Format",
        "menu.format.bold":     "Bold",
        "menu.format.italic":   "Italic",
        "menu.format.code":     "Code",
        "menu.format.h1":       "Heading 1",
        "menu.format.h2":       "Heading 2",
        "menu.format.h3":       "Heading 3",
        "menu.format.body":     "Body",
        "menu.format.ul":       "Bullet List",
        "menu.format.ol":       "Numbered List",
        "menu.format.quote":    "Blockquote",
        "menu.format.link":     "Insert Link",
        "menu.window":          "Window",
        "menu.window.minimize": "Minimize",
        "menu.window.zoom":     "Zoom",
        "menu.window.front":    "Bring All to Front",
        "menu.help":            "Help",
        "menu.help.help":       "Jena Note Help",
        "settings.title":       "Settings",
        "settings.language":    "Language",
        "settings.appearance":  "Color Mode",
        "appearance.system":    "System",
        "appearance.light":     "Light",
        "appearance.dark":      "Dark",
        "toolbar.bold":         "Bold",
        "toolbar.italic":       "Italic",
        "toolbar.code":         "Code",
        "toolbar.h1":           "H1",
        "toolbar.h2":           "H2",
        "toolbar.h3":           "H3",
        "toolbar.body":         "Body",
        "toolbar.ul":           "List",
        "toolbar.ol":           "Numbered",
        "toolbar.quote":        "Quote",
        "toolbar.link":         "Link",
        "toolbar.hr":           "Divider",
        "toolbar.lineSpacing":  "Line Spacing",
        "untitled":             "Untitled",
        "link.title":           "Insert Link",
        "link.message":         "Enter URL",
        "link.insert":          "Insert",
        "link.cancel":          "Cancel",
    ]

    private static let zh: [String: String] = [
        "menu.app.about":       "关于 Jena Note",
        "menu.app.hide":        "隐藏 Jena Note",
        "menu.app.hideOthers":  "隐藏其他",
        "menu.app.showAll":     "全部显示",
        "menu.app.settings":    "设置...",
        "menu.app.quit":        "退出 Jena Note",
        "menu.file":            "文件",
        "menu.file.new":        "新建文稿",
        "menu.file.open":       "打开...",
        "menu.file.recent":     "最近打开的文件",
        "menu.file.recent.empty":"无最近项目",
        "menu.file.recent.clear":"清除列表",
        "menu.file.save":       "保存",
        "menu.file.saveAs":     "另存为...",
        "menu.file.revert":     "恢复到已存储",
        "menu.file.close":      "关闭",
        "menu.edit":            "编辑",
        "menu.edit.undo":       "撤销",
        "menu.edit.redo":       "重做",
        "menu.edit.cut":        "剪切",
        "menu.edit.copy":       "复制",
        "menu.edit.paste":      "粘贴",
        "menu.edit.pastePlain":  "粘贴并匹配样式",
        "menu.edit.selectAll":  "全选",
        "menu.edit.find":       "查找...",
        "menu.format":          "格式",
        "menu.format.bold":     "粗体",
        "menu.format.italic":   "斜体",
        "menu.format.code":     "代码",
        "menu.format.h1":       "标题 1",
        "menu.format.h2":       "标题 2",
        "menu.format.h3":       "标题 3",
        "menu.format.body":     "正文",
        "menu.format.ul":       "项目列表",
        "menu.format.ol":       "编号列表",
        "menu.format.quote":    "引用",
        "menu.format.link":     "插入链接",
        "menu.window":          "窗口",
        "menu.window.minimize": "最小化",
        "menu.window.zoom":     "缩放",
        "menu.window.front":    "全部置于前面",
        "menu.help":            "帮助",
        "menu.help.help":       "Jena Note 帮助",
        "settings.title":       "设置",
        "settings.language":    "语言",
        "settings.appearance":  "颜色模式",
        "appearance.system":    "系统",
        "appearance.light":     "浅色",
        "appearance.dark":      "深色",
        "toolbar.bold":         "粗体",
        "toolbar.italic":       "斜体",
        "toolbar.code":         "代码",
        "toolbar.h1":           "H1",
        "toolbar.h2":           "H2",
        "toolbar.h3":           "H3",
        "toolbar.body":         "正文",
        "toolbar.ul":           "列表",
        "toolbar.ol":           "编号",
        "toolbar.quote":        "引用",
        "toolbar.link":         "链接",
        "toolbar.hr":           "分隔线",
        "toolbar.lineSpacing":  "行间距",
        "untitled":             "未命名",
        "link.title":           "插入链接",
        "link.message":         "请输入 URL",
        "link.insert":          "插入",
        "link.cancel":          "取消",
    ]

    private static let ja: [String: String] = [
        "menu.app.about":       "Jena Note について",
        "menu.app.hide":        "Jena Note を隠す",
        "menu.app.hideOthers":  "他を隠す",
        "menu.app.showAll":     "すべて表示",
        "menu.app.settings":    "設定...",
        "menu.app.quit":        "Jena Note を終了",
        "menu.file":            "ファイル",
        "menu.file.new":        "新規書類",
        "menu.file.open":       "開く...",
        "menu.file.recent":     "最近使った項目",
        "menu.file.recent.empty":"最近の項目なし",
        "menu.file.recent.clear":"リストを消去",
        "menu.file.save":       "保存",
        "menu.file.saveAs":     "別名で保存...",
        "menu.file.revert":     "保存した状態に戻す",
        "menu.file.close":      "閉じる",
        "menu.edit":            "編集",
        "menu.edit.undo":       "取り消す",
        "menu.edit.redo":       "やり直す",
        "menu.edit.cut":        "カット",
        "menu.edit.copy":       "コピー",
        "menu.edit.paste":      "ペースト",
        "menu.edit.pastePlain":  "ペーストしてスタイルを合わせる",
        "menu.edit.selectAll":  "すべてを選択",
        "menu.edit.find":       "検索...",
        "menu.format":          "フォーマット",
        "menu.format.bold":     "ボールド",
        "menu.format.italic":   "イタリック",
        "menu.format.code":     "コード",
        "menu.format.h1":       "見出し 1",
        "menu.format.h2":       "見出し 2",
        "menu.format.h3":       "見出し 3",
        "menu.format.body":     "本文",
        "menu.format.ul":       "箇条書き",
        "menu.format.ol":       "番号付きリスト",
        "menu.format.quote":    "引用",
        "menu.format.link":     "リンクを挿入",
        "menu.window":          "ウインドウ",
        "menu.window.minimize": "しまう",
        "menu.window.zoom":     "拡大/縮小",
        "menu.window.front":    "すべてを手前に移動",
        "menu.help":            "ヘルプ",
        "menu.help.help":       "Jena Note ヘルプ",
        "settings.title":       "設定",
        "settings.language":    "言語",
        "settings.appearance":  "カラーモード",
        "appearance.system":    "システム",
        "appearance.light":     "ライト",
        "appearance.dark":      "ダーク",
        "toolbar.bold":         "ボールド",
        "toolbar.italic":       "イタリック",
        "toolbar.code":         "コード",
        "toolbar.h1":           "H1",
        "toolbar.h2":           "H2",
        "toolbar.h3":           "H3",
        "toolbar.body":         "本文",
        "toolbar.ul":           "リスト",
        "toolbar.ol":           "番号",
        "toolbar.quote":        "引用",
        "toolbar.link":         "リンク",
        "toolbar.hr":           "区切り線",
        "toolbar.lineSpacing":  "行間隔",
        "untitled":             "名称未設定",
        "link.title":           "リンクを挿入",
        "link.message":         "URLを入力してください",
        "link.insert":          "挿入",
        "link.cancel":          "キャンセル",
    ]

    private static let es: [String: String] = [
        "menu.app.about":       "Acerca de Jena Note",
        "menu.app.hide":        "Ocultar Jena Note",
        "menu.app.hideOthers":  "Ocultar otros",
        "menu.app.showAll":     "Mostrar todo",
        "menu.app.settings":    "Ajustes...",
        "menu.app.quit":        "Salir de Jena Note",
        "menu.file":            "Archivo",
        "menu.file.new":        "Nuevo documento",
        "menu.file.open":       "Abrir...",
        "menu.file.recent":     "Abrir recientes",
        "menu.file.recent.empty":"Sin elementos recientes",
        "menu.file.recent.clear":"Borrar lista",
        "menu.file.save":       "Guardar",
        "menu.file.saveAs":     "Guardar como...",
        "menu.file.revert":     "Revertir",
        "menu.file.close":      "Cerrar",
        "menu.edit":            "Edición",
        "menu.edit.undo":       "Deshacer",
        "menu.edit.redo":       "Rehacer",
        "menu.edit.cut":        "Cortar",
        "menu.edit.copy":       "Copiar",
        "menu.edit.paste":      "Pegar",
        "menu.edit.pastePlain":  "Pegar con el estilo del destino",
        "menu.edit.selectAll":  "Seleccionar todo",
        "menu.edit.find":       "Buscar...",
        "menu.format":          "Formato",
        "menu.format.bold":     "Negrita",
        "menu.format.italic":   "Cursiva",
        "menu.format.code":     "Código",
        "menu.format.h1":       "Título 1",
        "menu.format.h2":       "Título 2",
        "menu.format.h3":       "Título 3",
        "menu.format.body":     "Cuerpo",
        "menu.format.ul":       "Lista con viñetas",
        "menu.format.ol":       "Lista numerada",
        "menu.format.quote":    "Cita",
        "menu.format.link":     "Insertar enlace",
        "menu.window":          "Ventana",
        "menu.window.minimize": "Minimizar",
        "menu.window.zoom":     "Zoom",
        "menu.window.front":    "Traer todo al frente",
        "menu.help":            "Ayuda",
        "menu.help.help":       "Ayuda de Jena Note",
        "settings.title":       "Ajustes",
        "settings.language":    "Idioma",
        "settings.appearance":  "Modo de color",
        "appearance.system":    "Sistema",
        "appearance.light":     "Claro",
        "appearance.dark":      "Oscuro",
        "toolbar.bold":         "Negrita",
        "toolbar.italic":       "Cursiva",
        "toolbar.code":         "Código",
        "toolbar.h1":           "H1",
        "toolbar.h2":           "H2",
        "toolbar.h3":           "H3",
        "toolbar.body":         "Cuerpo",
        "toolbar.ul":           "Lista",
        "toolbar.ol":           "Numerada",
        "toolbar.quote":        "Cita",
        "toolbar.link":         "Enlace",
        "toolbar.hr":           "Separador",
        "toolbar.lineSpacing":  "Interlineado",
        "untitled":             "Sin título",
        "link.title":           "Insertar enlace",
        "link.message":         "Introduzca la URL",
        "link.insert":          "Insertar",
        "link.cancel":          "Cancelar",
    ]

    private static let de: [String: String] = [
        "menu.app.about":       "Über Jena Note",
        "menu.app.hide":        "Jena Note ausblenden",
        "menu.app.hideOthers":  "Andere ausblenden",
        "menu.app.showAll":     "Alle einblenden",
        "menu.app.settings":    "Einstellungen...",
        "menu.app.quit":        "Jena Note beenden",
        "menu.file":            "Ablage",
        "menu.file.new":        "Neues Dokument",
        "menu.file.open":       "Öffnen...",
        "menu.file.recent":     "Zuletzt benutzte Dokumente",
        "menu.file.recent.empty":"Keine letzten Objekte",
        "menu.file.recent.clear":"Liste löschen",
        "menu.file.save":       "Sichern",
        "menu.file.saveAs":     "Sichern unter...",
        "menu.file.revert":     "Zurücksetzen",
        "menu.file.close":      "Schließen",
        "menu.edit":            "Bearbeiten",
        "menu.edit.undo":       "Widerrufen",
        "menu.edit.redo":       "Wiederholen",
        "menu.edit.cut":        "Ausschneiden",
        "menu.edit.copy":       "Kopieren",
        "menu.edit.paste":      "Einsetzen",
        "menu.edit.pastePlain":  "Einsetzen und Stil anpassen",
        "menu.edit.selectAll":  "Alles auswählen",
        "menu.edit.find":       "Suchen...",
        "menu.format":          "Format",
        "menu.format.bold":     "Fett",
        "menu.format.italic":   "Kursiv",
        "menu.format.code":     "Code",
        "menu.format.h1":       "Überschrift 1",
        "menu.format.h2":       "Überschrift 2",
        "menu.format.h3":       "Überschrift 3",
        "menu.format.body":     "Fließtext",
        "menu.format.ul":       "Aufzählung",
        "menu.format.ol":       "Nummerierte Liste",
        "menu.format.quote":    "Zitat",
        "menu.format.link":     "Link einfügen",
        "menu.window":          "Fenster",
        "menu.window.minimize": "Im Dock ablegen",
        "menu.window.zoom":     "Zoomen",
        "menu.window.front":    "Alle nach vorne bringen",
        "menu.help":            "Hilfe",
        "menu.help.help":       "Jena Note Hilfe",
        "settings.title":       "Einstellungen",
        "settings.language":    "Sprache",
        "settings.appearance":  "Farbmodus",
        "appearance.system":    "System",
        "appearance.light":     "Hell",
        "appearance.dark":      "Dunkel",
        "toolbar.bold":         "Fett",
        "toolbar.italic":       "Kursiv",
        "toolbar.code":         "Code",
        "toolbar.h1":           "H1",
        "toolbar.h2":           "H2",
        "toolbar.h3":           "H3",
        "toolbar.body":         "Text",
        "toolbar.ul":           "Liste",
        "toolbar.ol":           "Nummeriert",
        "toolbar.quote":        "Zitat",
        "toolbar.link":         "Link",
        "toolbar.hr":           "Trennlinie",
        "toolbar.lineSpacing":  "Zeilenabstand",
        "untitled":             "Ohne Titel",
        "link.title":           "Link einfügen",
        "link.message":         "URL eingeben",
        "link.insert":          "Einfügen",
        "link.cancel":          "Abbrechen",
    ]

    private static let fr: [String: String] = [
        "menu.app.about":       "À propos de Jena Note",
        "menu.app.hide":        "Masquer Jena Note",
        "menu.app.hideOthers":  "Masquer les autres",
        "menu.app.showAll":     "Tout afficher",
        "menu.app.settings":    "Réglages...",
        "menu.app.quit":        "Quitter Jena Note",
        "menu.file":            "Fichier",
        "menu.file.new":        "Nouveau document",
        "menu.file.open":       "Ouvrir...",
        "menu.file.recent":     "Ouvrir les éléments récents",
        "menu.file.recent.empty":"Aucun élément récent",
        "menu.file.recent.clear":"Effacer la liste",
        "menu.file.save":       "Enregistrer",
        "menu.file.saveAs":     "Enregistrer sous...",
        "menu.file.revert":     "Revenir à la version enregistrée",
        "menu.file.close":      "Fermer",
        "menu.edit":            "Édition",
        "menu.edit.undo":       "Annuler",
        "menu.edit.redo":       "Rétablir",
        "menu.edit.cut":        "Couper",
        "menu.edit.copy":       "Copier",
        "menu.edit.paste":      "Coller",
        "menu.edit.pastePlain":  "Coller et adapter le style",
        "menu.edit.selectAll":  "Tout sélectionner",
        "menu.edit.find":       "Rechercher...",
        "menu.format":          "Format",
        "menu.format.bold":     "Gras",
        "menu.format.italic":   "Italique",
        "menu.format.code":     "Code",
        "menu.format.h1":       "Titre 1",
        "menu.format.h2":       "Titre 2",
        "menu.format.h3":       "Titre 3",
        "menu.format.body":     "Corps",
        "menu.format.ul":       "Liste à puces",
        "menu.format.ol":       "Liste numérotée",
        "menu.format.quote":    "Citation",
        "menu.format.link":     "Insérer un lien",
        "menu.window":          "Fenêtre",
        "menu.window.minimize": "Réduire",
        "menu.window.zoom":     "Agrandir",
        "menu.window.front":    "Tout ramener au premier plan",
        "menu.help":            "Aide",
        "menu.help.help":       "Aide Jena Note",
        "settings.title":       "Réglages",
        "settings.language":    "Langue",
        "settings.appearance":  "Mode couleur",
        "appearance.system":    "Système",
        "appearance.light":     "Clair",
        "appearance.dark":      "Sombre",
        "toolbar.bold":         "Gras",
        "toolbar.italic":       "Italique",
        "toolbar.code":         "Code",
        "toolbar.h1":           "H1",
        "toolbar.h2":           "H2",
        "toolbar.h3":           "H3",
        "toolbar.body":         "Corps",
        "toolbar.ul":           "Liste",
        "toolbar.ol":           "Numérotée",
        "toolbar.quote":        "Citation",
        "toolbar.link":         "Lien",
        "toolbar.hr":           "Séparateur",
        "toolbar.lineSpacing":  "Interligne",
        "untitled":             "Sans titre",
        "link.title":           "Insérer un lien",
        "link.message":         "Entrez l'URL",
        "link.insert":          "Insérer",
        "link.cancel":          "Annuler",
    ]
}
