import Foundation

// MARK: - Localization

enum L10n {

    static func tr(_ key: String) -> String {
        let lang = SettingsManager.shared.language
        return translations[lang]?[key] ?? translations[.en]?[key] ?? key
    }

    // MARK: - Translation Tables

    private static let translations: [SettingsManager.Language: [String: String]] = [
        .ko: ko, .en: en, .zh: zh, .ja: ja, .es: es, .de: de, .fr: fr
    ]

    private static let ko: [String: String] = [
        // App Menu
        "menu.app.about":       "Jena Note 정보",
        "menu.app.hide":        "Jena Note 숨기기",
        "menu.app.hideOthers":  "다른 항목 숨기기",
        "menu.app.showAll":     "모두 보기",
        "menu.app.settings":    "설정...",
        "menu.app.quit":        "Jena Note 종료",
        // File Menu
        "menu.file":            "파일",
        "menu.file.new":        "새 문서",
        "menu.file.open":       "열기...",
        "menu.file.addFolder":  "폴더 추가...",
        "menu.file.recent":     "최근 열었던 항목",
        "menu.file.recent.empty":"최근 항목 없음",
        "menu.file.recent.clear":"목록 지우기",
        "menu.file.save":       "저장",
        "menu.file.saveAs":     "다른 이름으로 저장...",
        "menu.file.export":     "내보내기...",
        "menu.file.export.docx":"Word 문서 (.docx)",
        "menu.file.export.hwpx":"한글 문서 (.hwpx)",
        "export.error.title":   "내보내기 실패",
        "export.error.message": "파일을 저장하지 못했어요.",
        "export.warn.title":    "일부 이미지 제외됨",
        "export.warn.imageSkipped": "이미지 %d개를 내보내지 못해 건너뛰었어요.",
        "menu.file.revert":     "되돌리기",
        "menu.file.close":      "닫기",
        // View Menu
        "menu.view":            "보기",
        "menu.view.toggleSidebar": "사이드바 표시/숨기기",
        "menu.view.readingMode": "읽기 모드",
        // Reader toolbar
        "reader.exit":          "편집으로",
        "reader.pageMode":      "보기 방식",
        "reader.scroll":        "스크롤",
        "reader.paged":         "페이징",
        "reader.width":         "폭",
        "reader.widthMobile":   "모바일",
        "reader.widthBook":     "책",
        "reader.fontDown":      "글자 작게",
        "reader.fontUp":        "글자 크게",
        "reader.font":          "글꼴",
        "status.charCount":     "%@자 · 공백 포함 %@자",
        "reader.serif":         "명조",
        "reader.sans":          "고딕",
        "reader.lineSpacing":   "행간",
        "reader.lineTight":     "좁게",
        "reader.lineNormal":    "보통",
        "reader.lineWide":      "넓게",
        // Sidebar
        "sidebar.title":        "폴더",
        "sidebar.tab.folders":  "폴더",
        "sidebar.tab.images":   "이미지",
        "sidebar.images.empty": "첨부된 이미지가 없어요",
        "sidebar.empty.message": "폴더를 추가해 시작하세요",
        "sidebar.empty.button": "폴더 추가…",
        "sidebar.add.tooltip":  "폴더 추가",
        "sidebar.sort.tooltip": "정렬",
        "sidebar.sort.name":    "이름순",
        "sidebar.sort.date":    "수정일순",
        "sidebar.sort.asc":     "오름차순",
        "sidebar.sort.desc":    "내림차순",
        "sidebar.context.remove":"사이드바에서 제거",
        "sidebar.context.reveal":"Finder에서 보기",
        "sidebar.missing":      "찾을 수 없음",
        "sidebar.locate":       "위치 찾기…",
        "sidebar.openPanel.title": "사이드바에 추가할 폴더 선택",
        "sidebar.openPanel.prompt":"폴더 추가",
        // External change
        "external.deleted.title":  "이 파일이 외부에서 삭제되었습니다",
        "external.deleted.saveAs":"다른 이름으로 저장",
        "external.deleted.close":  "닫기",
        // Save confirm sheet (sidebar swap)
        "confirm.save.message":  "이 문서의 변경 사항을 저장하시겠습니까?",
        "confirm.save.info":     "저장하지 않으면 변경 사항이 사라집니다.",
        "confirm.save":          "저장",
        "confirm.dontSave":      "저장 안 함",
        "confirm.cancel":        "취소",
        // Edit Menu
        "menu.edit":            "편집",
        "menu.edit.undo":       "실행 취소",
        "menu.edit.redo":       "다시 실행",
        "menu.edit.cut":        "오려두기",
        "menu.edit.copy":       "복사",
        "menu.edit.paste":      "붙여넣기",
        "menu.edit.pastePlain":  "서식 없이 붙여넣기",
        "menu.edit.selectAll":  "전체 선택",
        "menu.edit.find":       "찾기...",
        // Format Menu
        "menu.format":          "서식",
        "menu.format.bold":     "굵게",
        "menu.format.italic":   "기울임",
        "menu.format.code":     "코드",
        "menu.format.h1":       "제목 1",
        "menu.format.h2":       "제목 2",
        "menu.format.h3":       "제목 3",
        "menu.format.body":     "본문",
        "menu.format.ul":       "목록",
        "menu.format.ol":       "번호 목록",
        "menu.format.quote":    "인용",
        "menu.format.link":     "링크 삽입",
        "menu.format.textColor":"글자 색...",
        // Window Menu
        "menu.window":          "윈도우",
        "menu.window.minimize": "최소화",
        "menu.window.zoom":     "확대/축소",
        "menu.window.front":    "모든 창 앞으로",
        // Help Menu
        "menu.help":            "도움말",
        "menu.help.help":       "Jena Note 도움말",
        // Settings
        "settings.title":       "설정",
        "settings.language":    "언어",
        "settings.appearance":  "컬러 모드",
        "appearance.system":    "시스템",
        "appearance.light":     "라이트",
        "appearance.dark":      "다크",
        // Toolbar
        "toolbar.bold":         "굵게",
        "toolbar.italic":       "기울임",
        "toolbar.code":         "코드",
        "toolbar.h1":           "H1",
        "toolbar.h2":           "H2",
        "toolbar.h3":           "H3",
        "toolbar.body":         "본문",
        "toolbar.ul":           "목록",
        "toolbar.ol":           "번호 목록",
        "toolbar.quote":        "인용",
        "toolbar.link":         "링크",
        "toolbar.hr":           "구분선",
        "toolbar.textColor":    "글자 색",
        "toolbar.lineSpacing":  "줄 간격",
        // Misc
        "untitled":             "제목 없음",
        "link.title":           "링크 삽입",
        "link.message":         "URL을 입력하세요",
        "link.insert":          "삽입",
        "link.cancel":          "취소",
        // Help
        "help.title":           "Jena Note 도움말",
        "help.intro":           "Jena Note는 macOS용 마크다운 편집기입니다. 마크다운 기호 없이 서식이 적용된 상태로 편집하며, 저장 시 표준 CommonMark 형식의 .md 파일로 내보냅니다.",
        "help.file":            "파일 관리",
        "help.file.new":        "새 문서",
        "help.file.new.d":      "파일 > 새 문서 (⌘N) — 빈 문서를 새 창으로 엽니다.",
        "help.file.open":       "파일 열기",
        "help.file.open.d":     "파일 > 열기 (⌘O) — .md 파일을 선택해 엽니다.",
        "help.file.save":       "저장",
        "help.file.save.d":     "파일 > 저장 (⌘S) — 현재 문서를 저장합니다.",
        "help.file.saveAs":     "다른 이름으로 저장",
        "help.file.saveAs.d":   "파일 > 다른 이름으로 저장 (⇧⌘S) — 새 파일명으로 저장합니다.",
        "help.file.recent":     "최근 문서",
        "help.file.recent.d":   "파일 > 최근 열었던 항목 — 최근 열었던 파일 목록을 표시합니다. 앱 재시작 시 가장 최근 파일이 자동으로 열립니다.",
        "help.format":          "텍스트 서식",
        "help.format.intro":    "텍스트를 선택한 뒤 툴바 버튼 또는 단축키로 서식을 적용합니다.",
        "help.format.inline":   "인라인 서식",
        "help.format.bold":     "굵게",
        "help.format.italic":   "기울임",
        "help.format.code":     "인라인 코드",
        "help.format.code.d":   "툴바 버튼 사용 (텍스트 선택 필요)",
        "help.format.link":     "링크 삽입",
        "help.format.link.d":   "⌘K (텍스트 선택 필요)",
        "help.format.para":     "단락 서식",
        "help.format.body":     "본문",
        "help.format.body.d":   "서식 > 본문",
        "help.format.h1":       "제목 1",
        "help.format.h1.d":     "서식 > 제목 1",
        "help.format.h2":       "제목 2",
        "help.format.h2.d":     "서식 > 제목 2",
        "help.format.h3":       "제목 3",
        "help.format.h3.d":     "서식 > 제목 3",
        "help.format.ul":       "글머리 기호 목록",
        "help.format.ul.d":     "서식 > 목록",
        "help.format.ol":       "번호 목록",
        "help.format.ol.d":     "서식 > 번호 목록",
        "help.format.quote":    "인용",
        "help.format.quote.d":  "서식 > 인용",
        "help.format.hr":       "수평선",
        "help.format.hr.d":     "서식 > 구분선 또는 툴바 ─ 버튼",
        "help.spacing":         "줄 간격",
        "help.spacing.d":       "툴바 오른쪽의 1× · 1.5× · 2× 세그먼트 컨트롤로 전체 줄 간격을 조절합니다.",
        "help.edit":            "편집",
        "help.edit.undo":       "실행 취소",
        "help.edit.redo":       "다시 실행",
        "help.edit.cut":        "오려두기",
        "help.edit.copy":       "복사",
        "help.edit.paste":      "붙여넣기",
        "help.edit.pastePlain":  "서식 없이 붙여넣기",
        "help.edit.selectAll":  "전체 선택",
        "help.edit.find":       "찾기",
        "help.fileFormat":      "파일 형식",
        "help.fileFormat.d":    "Jena Note는 UTF-8 인코딩의 CommonMark 형식(.md)을 읽고 씁니다. 저장된 파일은 모든 표준 마크다운 편집기 및 뷰어와 호환됩니다.",
    ]

    private static let en: [String: String] = [
        "menu.app.about":       "About Jena Note",
        "menu.app.hide":        "Hide Jena Note",
        "menu.app.hideOthers":  "Hide Others",
        "menu.app.showAll":     "Show All",
        "menu.app.settings":    "Settings...",
        "menu.app.quit":        "Quit Jena Note",
        "menu.file":            "File",
        "menu.file.new":        "New Document",
        "menu.file.open":       "Open...",
        "menu.file.addFolder":  "Add Folder...",
        "menu.file.recent":     "Open Recent",
        "menu.file.recent.empty":"No Recent Items",
        "menu.file.recent.clear":"Clear List",
        "menu.file.save":       "Save",
        "menu.file.saveAs":     "Save As...",
        "menu.file.export":     "Export...",
        "menu.file.export.docx":"Word Document (.docx)",
        "menu.file.export.hwpx":"Hangul Document (.hwpx)",
        "export.error.title":   "Export Failed",
        "export.error.message": "Could not save the file.",
        "export.warn.title":    "Some Images Skipped",
        "export.warn.imageSkipped": "%d image(s) could not be exported and were skipped.",
        "menu.file.revert":     "Revert to Saved",
        "menu.file.close":      "Close",
        "menu.view":            "View",
        "menu.view.toggleSidebar":"Toggle Sidebar",
        "menu.view.readingMode":"Reading Mode",
        "reader.exit":          "Edit",
        "reader.pageMode":      "Layout",
        "reader.scroll":        "Scroll",
        "reader.paged":         "Paged",
        "reader.width":         "Width",
        "reader.widthMobile":   "Mobile",
        "reader.widthBook":     "Book",
        "reader.fontDown":      "Smaller Text",
        "reader.fontUp":        "Larger Text",
        "reader.font":          "Font",
        "status.charCount":     "%@ chars · %@ with spaces",
        "reader.serif":         "Serif",
        "reader.sans":          "Sans",
        "reader.lineSpacing":   "Line Spacing",
        "reader.lineTight":     "Tight",
        "reader.lineNormal":    "Normal",
        "reader.lineWide":      "Wide",
        "sidebar.title":        "Folders",
        "sidebar.tab.folders":  "Folders",
        "sidebar.tab.images":   "Images",
        "sidebar.images.empty": "No attached images",
        "sidebar.empty.message":"Add a folder to get started",
        "sidebar.empty.button": "Add Folder…",
        "sidebar.add.tooltip":  "Add Folder",
        "sidebar.sort.tooltip": "Sort",
        "sidebar.sort.name":    "By Name",
        "sidebar.sort.date":    "By Date Modified",
        "sidebar.sort.asc":     "Ascending",
        "sidebar.sort.desc":    "Descending",
        "sidebar.context.remove":"Remove from Sidebar",
        "sidebar.context.reveal":"Reveal in Finder",
        "sidebar.missing":      "Not Found",
        "sidebar.locate":       "Locate…",
        "sidebar.openPanel.title":"Choose a folder to add",
        "sidebar.openPanel.prompt":"Add Folder",
        "external.deleted.title":"This file was deleted externally",
        "external.deleted.saveAs":"Save As…",
        "external.deleted.close":"Close",
        "confirm.save.message": "Do you want to save the changes to this document?",
        "confirm.save.info":    "Your changes will be lost if you don't save them.",
        "confirm.save":         "Save",
        "confirm.dontSave":     "Don't Save",
        "confirm.cancel":       "Cancel",
        "menu.edit":            "Edit",
        "menu.edit.undo":       "Undo",
        "menu.edit.redo":       "Redo",
        "menu.edit.cut":        "Cut",
        "menu.edit.copy":       "Copy",
        "menu.edit.paste":      "Paste",
        "menu.edit.pastePlain":  "Paste and Match Style",
        "menu.edit.selectAll":  "Select All",
        "menu.edit.find":       "Find...",
        "menu.format":          "Format",
        "menu.format.bold":     "Bold",
        "menu.format.italic":   "Italic",
        "menu.format.code":     "Code",
        "menu.format.h1":       "Heading 1",
        "menu.format.h2":       "Heading 2",
        "menu.format.h3":       "Heading 3",
        "menu.format.body":     "Body",
        "menu.format.ul":       "Bullet List",
        "menu.format.ol":       "Numbered List",
        "menu.format.quote":    "Blockquote",
        "menu.format.link":     "Insert Link",
        "menu.format.textColor":"Text Color...",
        "menu.window":          "Window",
        "menu.window.minimize": "Minimize",
        "menu.window.zoom":     "Zoom",
        "menu.window.front":    "Bring All to Front",
        "menu.help":            "Help",
        "menu.help.help":       "Jena Note Help",
        "settings.title":       "Settings",
        "settings.language":    "Language",
        "settings.appearance":  "Color Mode",
        "appearance.system":    "System",
        "appearance.light":     "Light",
        "appearance.dark":      "Dark",
        "toolbar.bold":         "Bold",
        "toolbar.italic":       "Italic",
        "toolbar.code":         "Code",
        "toolbar.h1":           "H1",
        "toolbar.h2":           "H2",
        "toolbar.h3":           "H3",
        "toolbar.body":         "Body",
        "toolbar.ul":           "List",
        "toolbar.ol":           "Numbered",
        "toolbar.quote":        "Quote",
        "toolbar.link":         "Link",
        "toolbar.hr":           "Divider",
        "toolbar.textColor":    "Text Color",
        "toolbar.lineSpacing":  "Line Spacing",
        "untitled":             "Untitled",
        "link.title":           "Insert Link",
        "link.message":         "Enter URL",
        "link.insert":          "Insert",
        "link.cancel":          "Cancel",
        "help.title":           "Jena Note Help",
        "help.intro":           "Jena Note is a Markdown editor for macOS. Edit with formatting applied visually — no Markdown symbols shown — and save as standard CommonMark .md files.",
        "help.file":            "File Management",
        "help.file.new":        "New Document",
        "help.file.new.d":      "File > New Document (⌘N) — Opens a blank document in a new window.",
        "help.file.open":       "Open File",
        "help.file.open.d":     "File > Open (⌘O) — Select and open a .md file.",
        "help.file.save":       "Save",
        "help.file.save.d":     "File > Save (⌘S) — Save the current document.",
        "help.file.saveAs":     "Save As",
        "help.file.saveAs.d":   "File > Save As (⇧⌘S) — Save with a new filename.",
        "help.file.recent":     "Recent Documents",
        "help.file.recent.d":   "File > Open Recent — Shows recently opened files. The most recent file is restored on relaunch.",
        "help.format":          "Text Formatting",
        "help.format.intro":    "Select text, then use toolbar buttons or keyboard shortcuts to apply formatting.",
        "help.format.inline":   "Inline Formatting",
        "help.format.bold":     "Bold",
        "help.format.italic":   "Italic",
        "help.format.code":     "Inline Code",
        "help.format.code.d":   "Use toolbar button (text selection required)",
        "help.format.link":     "Insert Link",
        "help.format.link.d":   "⌘K (text selection required)",
        "help.format.para":     "Paragraph Formatting",
        "help.format.body":     "Body",
        "help.format.body.d":   "Format > Body",
        "help.format.h1":       "Heading 1",
        "help.format.h1.d":     "Format > Heading 1",
        "help.format.h2":       "Heading 2",
        "help.format.h2.d":     "Format > Heading 2",
        "help.format.h3":       "Heading 3",
        "help.format.h3.d":     "Format > Heading 3",
        "help.format.ul":       "Bullet List",
        "help.format.ul.d":     "Format > Bullet List",
        "help.format.ol":       "Numbered List",
        "help.format.ol.d":     "Format > Numbered List",
        "help.format.quote":    "Blockquote",
        "help.format.quote.d":  "Format > Blockquote",
        "help.format.hr":       "Horizontal Rule",
        "help.format.hr.d":     "Format > Divider or toolbar ─ button",
        "help.spacing":         "Line Spacing",
        "help.spacing.d":       "Use the 1× · 1.5× · 2× segmented control on the right side of the toolbar to adjust line spacing.",
        "help.edit":            "Editing",
        "help.edit.undo":       "Undo",
        "help.edit.redo":       "Redo",
        "help.edit.cut":        "Cut",
        "help.edit.copy":       "Copy",
        "help.edit.paste":      "Paste",
        "help.edit.pastePlain":  "Paste and Match Style",
        "help.edit.selectAll":  "Select All",
        "help.edit.find":       "Find",
        "help.fileFormat":      "File Format",
        "help.fileFormat.d":    "Jena Note reads and writes CommonMark format (.md) with UTF-8 encoding. Saved files are compatible with all standard Markdown editors and viewers.",
    ]

    private static let zh: [String: String] = [
        // View Menu (reader)
        "menu.view.readingMode":"阅读模式",
        // Reader toolbar
        "reader.exit":          "编辑",
        "reader.pageMode":      "翻页方式",
        "reader.scroll":        "滚动",
        "reader.paged":         "翻页",
        "reader.width":         "宽度",
        "reader.widthMobile":   "手机",
        "reader.widthBook":     "书本",
        "reader.fontDown":      "缩小",
        "reader.fontUp":        "放大",
        "reader.font":          "字体",
        "status.charCount":     "%@字 · 含空格 %@字",
        "reader.serif":         "宋体",
        "reader.sans":          "黑体",
        "reader.lineSpacing":   "行距",
        "reader.lineTight":     "紧凑",
        "reader.lineNormal":    "标准",
        "reader.lineWide":      "宽松",
        "menu.app.about":       "关于 Jena Note",
        "menu.app.hide":        "隐藏 Jena Note",
        "menu.app.hideOthers":  "隐藏其他",
        "menu.app.showAll":     "全部显示",
        "menu.app.settings":    "设置...",
        "menu.app.quit":        "退出 Jena Note",
        "menu.file":            "文件",
        "menu.file.new":        "新建文稿",
        "menu.file.open":       "打开...",
        "menu.file.recent":     "最近打开的文件",
        "menu.file.recent.empty":"无最近项目",
        "menu.file.recent.clear":"清除列表",
        "menu.file.save":       "保存",
        "menu.file.saveAs":     "另存为...",
        "menu.file.export":     "导出...",
        "menu.file.export.docx":"Word 文档 (.docx)",
        "menu.file.export.hwpx":"韩文文档 (.hwpx)",
        "export.error.title":   "导出失败",
        "export.error.message": "无法保存文件。",
        "export.warn.title":    "部分图片被跳过",
        "export.warn.imageSkipped": "有 %d 张图片无法导出，已跳过。",
        "menu.file.revert":     "恢复到已存储",
        "menu.file.close":      "关闭",
        "menu.edit":            "编辑",
        "menu.edit.undo":       "撤销",
        "menu.edit.redo":       "重做",
        "menu.edit.cut":        "剪切",
        "menu.edit.copy":       "复制",
        "menu.edit.paste":      "粘贴",
        "menu.edit.pastePlain":  "粘贴并匹配样式",
        "menu.edit.selectAll":  "全选",
        "menu.edit.find":       "查找...",
        "menu.format":          "格式",
        "menu.format.bold":     "粗体",
        "menu.format.italic":   "斜体",
        "menu.format.code":     "代码",
        "menu.format.h1":       "标题 1",
        "menu.format.h2":       "标题 2",
        "menu.format.h3":       "标题 3",
        "menu.format.body":     "正文",
        "menu.format.ul":       "项目列表",
        "menu.format.ol":       "编号列表",
        "menu.format.quote":    "引用",
        "menu.format.link":     "插入链接",
        "menu.window":          "窗口",
        "menu.window.minimize": "最小化",
        "menu.window.zoom":     "缩放",
        "menu.window.front":    "全部置于前面",
        "menu.help":            "帮助",
        "menu.help.help":       "Jena Note 帮助",
        "settings.title":       "设置",
        "settings.language":    "语言",
        "settings.appearance":  "颜色模式",
        "appearance.system":    "系统",
        "appearance.light":     "浅色",
        "appearance.dark":      "深色",
        "toolbar.bold":         "粗体",
        "toolbar.italic":       "斜体",
        "toolbar.code":         "代码",
        "toolbar.h1":           "H1",
        "toolbar.h2":           "H2",
        "toolbar.h3":           "H3",
        "toolbar.body":         "正文",
        "toolbar.ul":           "列表",
        "toolbar.ol":           "编号",
        "toolbar.quote":        "引用",
        "toolbar.link":         "链接",
        "toolbar.hr":           "分隔线",
        "toolbar.lineSpacing":  "行间距",
        "untitled":             "未命名",
        "link.title":           "插入链接",
        "link.message":         "请输入 URL",
        "link.insert":          "插入",
        "link.cancel":          "取消",
        "help.title":           "Jena Note 帮助",
        "help.intro":           "Jena Note 是一款 macOS Markdown 编辑器。无需看到 Markdown 符号，直接以可视化格式编辑，保存为标准 CommonMark .md 文件。",
        "help.file":            "文件管理",
        "help.file.new":        "新建文稿",
        "help.file.new.d":      "文件 > 新建文稿 (⌘N) — 在新窗口中打开空白文稿。",
        "help.file.open":       "打开文件",
        "help.file.open.d":     "文件 > 打开 (⌘O) — 选择并打开 .md 文件。",
        "help.file.save":       "保存",
        "help.file.save.d":     "文件 > 保存 (⌘S) — 保存当前文稿。",
        "help.file.saveAs":     "另存为",
        "help.file.saveAs.d":   "文件 > 另存为 (⇧⌘S) — 以新文件名保存。",
        "help.file.recent":     "最近文稿",
        "help.file.recent.d":   "文件 > 最近打开的文件 — 显示最近打开的文件列表。重新启动时自动打开最近的文件。",
        "help.format":          "文本格式",
        "help.format.intro":    "选择文本后，使用工具栏按钮或快捷键应用格式。",
        "help.format.inline":   "内联格式",
        "help.format.bold":     "粗体",
        "help.format.italic":   "斜体",
        "help.format.code":     "内联代码",
        "help.format.code.d":   "使用工具栏按钮（需要选择文本）",
        "help.format.link":     "插入链接",
        "help.format.link.d":   "⌘K（需要选择文本）",
        "help.format.para":     "段落格式",
        "help.format.body":     "正文",
        "help.format.body.d":   "格式 > 正文",
        "help.format.h1":       "标题 1",
        "help.format.h1.d":     "格式 > 标题 1",
        "help.format.h2":       "标题 2",
        "help.format.h2.d":     "格式 > 标题 2",
        "help.format.h3":       "标题 3",
        "help.format.h3.d":     "格式 > 标题 3",
        "help.format.ul":       "项目列表",
        "help.format.ul.d":     "格式 > 项目列表",
        "help.format.ol":       "编号列表",
        "help.format.ol.d":     "格式 > 编号列表",
        "help.format.quote":    "引用",
        "help.format.quote.d":  "格式 > 引用",
        "help.format.hr":       "水平线",
        "help.format.hr.d":     "格式 > 分隔线或工具栏 ─ 按钮",
        "help.spacing":         "行间距",
        "help.spacing.d":       "使用工具栏右侧的 1× · 1.5× · 2× 分段控件调整整体行间距。",
        "help.edit":            "编辑",
        "help.edit.undo":       "撤销",
        "help.edit.redo":       "重做",
        "help.edit.cut":        "剪切",
        "help.edit.copy":       "复制",
        "help.edit.paste":      "粘贴",
        "help.edit.pastePlain":  "粘贴并匹配样式",
        "help.edit.selectAll":  "全选",
        "help.edit.find":       "查找",
        "help.fileFormat":      "文件格式",
        "help.fileFormat.d":    "Jena Note 读取和写入 UTF-8 编码的 CommonMark 格式（.md）。保存的文件与所有标准 Markdown 编辑器和查看器兼容。",
    ]

    private static let ja: [String: String] = [
        // View Menu (reader)
        "menu.view.readingMode":"読書モード",
        // Reader toolbar
        "reader.exit":          "編集",
        "reader.pageMode":      "ページ方式",
        "reader.scroll":        "スクロール",
        "reader.paged":         "ページ",
        "reader.width":         "幅",
        "reader.widthMobile":   "モバイル",
        "reader.widthBook":     "本",
        "reader.fontDown":      "小さく",
        "reader.fontUp":        "大きく",
        "reader.font":          "フォント",
        "status.charCount":     "%@字 · 空白込み %@字",
        "reader.serif":         "明朝",
        "reader.sans":          "ゴシック",
        "reader.lineSpacing":   "行間",
        "reader.lineTight":     "狭い",
        "reader.lineNormal":    "標準",
        "reader.lineWide":      "広い",
        "menu.app.about":       "Jena Note について",
        "menu.app.hide":        "Jena Note を隠す",
        "menu.app.hideOthers":  "他を隠す",
        "menu.app.showAll":     "すべて表示",
        "menu.app.settings":    "設定...",
        "menu.app.quit":        "Jena Note を終了",
        "menu.file":            "ファイル",
        "menu.file.new":        "新規書類",
        "menu.file.open":       "開く...",
        "menu.file.recent":     "最近使った項目",
        "menu.file.recent.empty":"最近の項目なし",
        "menu.file.recent.clear":"リストを消去",
        "menu.file.save":       "保存",
        "menu.file.saveAs":     "別名で保存...",
        "menu.file.export":     "書き出す...",
        "menu.file.export.docx":"Word 書類 (.docx)",
        "menu.file.export.hwpx":"HWP 書類 (.hwpx)",
        "export.error.title":   "書き出しに失敗しました",
        "export.error.message": "ファイルを保存できませんでした。",
        "export.warn.title":    "一部の画像をスキップしました",
        "export.warn.imageSkipped": "%d 個の画像を書き出せずスキップしました。",
        "menu.file.revert":     "保存した状態に戻す",
        "menu.file.close":      "閉じる",
        "menu.edit":            "編集",
        "menu.edit.undo":       "取り消す",
        "menu.edit.redo":       "やり直す",
        "menu.edit.cut":        "カット",
        "menu.edit.copy":       "コピー",
        "menu.edit.paste":      "ペースト",
        "menu.edit.pastePlain":  "ペーストしてスタイルを合わせる",
        "menu.edit.selectAll":  "すべてを選択",
        "menu.edit.find":       "検索...",
        "menu.format":          "フォーマット",
        "menu.format.bold":     "ボールド",
        "menu.format.italic":   "イタリック",
        "menu.format.code":     "コード",
        "menu.format.h1":       "見出し 1",
        "menu.format.h2":       "見出し 2",
        "menu.format.h3":       "見出し 3",
        "menu.format.body":     "本文",
        "menu.format.ul":       "箇条書き",
        "menu.format.ol":       "番号付きリスト",
        "menu.format.quote":    "引用",
        "menu.format.link":     "リンクを挿入",
        "menu.window":          "ウインドウ",
        "menu.window.minimize": "しまう",
        "menu.window.zoom":     "拡大/縮小",
        "menu.window.front":    "すべてを手前に移動",
        "menu.help":            "ヘルプ",
        "menu.help.help":       "Jena Note ヘルプ",
        "settings.title":       "設定",
        "settings.language":    "言語",
        "settings.appearance":  "カラーモード",
        "appearance.system":    "システム",
        "appearance.light":     "ライト",
        "appearance.dark":      "ダーク",
        "toolbar.bold":         "ボールド",
        "toolbar.italic":       "イタリック",
        "toolbar.code":         "コード",
        "toolbar.h1":           "H1",
        "toolbar.h2":           "H2",
        "toolbar.h3":           "H3",
        "toolbar.body":         "本文",
        "toolbar.ul":           "リスト",
        "toolbar.ol":           "番号",
        "toolbar.quote":        "引用",
        "toolbar.link":         "リンク",
        "toolbar.hr":           "区切り線",
        "toolbar.lineSpacing":  "行間隔",
        "untitled":             "名称未設定",
        "link.title":           "リンクを挿入",
        "link.message":         "URLを入力してください",
        "link.insert":          "挿入",
        "link.cancel":          "キャンセル",
        "help.title":           "Jena Note ヘルプ",
        "help.intro":           "Jena Note は macOS 用の Markdown エディタです。Markdown 記号を表示せず、書式が適用された状態で編集し、標準 CommonMark 形式の .md ファイルとして保存します。",
        "help.file":            "ファイル管理",
        "help.file.new":        "新規書類",
        "help.file.new.d":      "ファイル > 新規書類 (⌘N) — 新しいウインドウに空白の書類を開きます。",
        "help.file.open":       "ファイルを開く",
        "help.file.open.d":     "ファイル > 開く (⌘O) — .md ファイルを選択して開きます。",
        "help.file.save":       "保存",
        "help.file.save.d":     "ファイル > 保存 (⌘S) — 現在の書類を保存します。",
        "help.file.saveAs":     "別名で保存",
        "help.file.saveAs.d":   "ファイル > 別名で保存 (⇧⌘S) — 新しいファイル名で保存します。",
        "help.file.recent":     "最近の書類",
        "help.file.recent.d":   "ファイル > 最近使った項目 — 最近開いたファイルの一覧を表示します。再起動時に最後のファイルが自動的に開きます。",
        "help.format":          "テキスト書式",
        "help.format.intro":    "テキストを選択し、ツールバーボタンまたはキーボードショートカットで書式を適用します。",
        "help.format.inline":   "インライン書式",
        "help.format.bold":     "ボールド",
        "help.format.italic":   "イタリック",
        "help.format.code":     "インラインコード",
        "help.format.code.d":   "ツールバーボタンを使用（テキスト選択が必要）",
        "help.format.link":     "リンクを挿入",
        "help.format.link.d":   "⌘K（テキスト選択が必要）",
        "help.format.para":     "段落書式",
        "help.format.body":     "本文",
        "help.format.body.d":   "フォーマット > 本文",
        "help.format.h1":       "見出し 1",
        "help.format.h1.d":     "フォーマット > 見出し 1",
        "help.format.h2":       "見出し 2",
        "help.format.h2.d":     "フォーマット > 見出し 2",
        "help.format.h3":       "見出し 3",
        "help.format.h3.d":     "フォーマット > 見出し 3",
        "help.format.ul":       "箇条書き",
        "help.format.ul.d":     "フォーマット > 箇条書き",
        "help.format.ol":       "番号付きリスト",
        "help.format.ol.d":     "フォーマット > 番号付きリスト",
        "help.format.quote":    "引用",
        "help.format.quote.d":  "フォーマット > 引用",
        "help.format.hr":       "水平線",
        "help.format.hr.d":     "フォーマット > 区切り線またはツールバー ─ ボタン",
        "help.spacing":         "行間隔",
        "help.spacing.d":       "ツールバー右側の 1× · 1.5× · 2× セグメントコントロールで行間隔を調整します。",
        "help.edit":            "編集",
        "help.edit.undo":       "取り消す",
        "help.edit.redo":       "やり直す",
        "help.edit.cut":        "カット",
        "help.edit.copy":       "コピー",
        "help.edit.paste":      "ペースト",
        "help.edit.pastePlain":  "ペーストしてスタイルを合わせる",
        "help.edit.selectAll":  "すべてを選択",
        "help.edit.find":       "検索",
        "help.fileFormat":      "ファイル形式",
        "help.fileFormat.d":    "Jena Note は UTF-8 エンコーディングの CommonMark 形式（.md）を読み書きします。保存したファイルはすべての標準 Markdown エディタおよびビューアと互換性があります。",
    ]

    private static let es: [String: String] = [
        // View Menu (reader)
        "menu.view.readingMode":"Modo lectura",
        // Reader toolbar
        "reader.exit":          "Editar",
        "reader.pageMode":      "Modo de página",
        "reader.scroll":        "Desplazar",
        "reader.paged":         "Páginas",
        "reader.width":         "Ancho",
        "reader.widthMobile":   "Móvil",
        "reader.widthBook":     "Libro",
        "reader.fontDown":      "Reducir",
        "reader.fontUp":        "Ampliar",
        "reader.font":          "Fuente",
        "status.charCount":     "%@ caracteres · %@ con espacios",
        "reader.serif":         "Serif",
        "reader.sans":          "Sans",
        "reader.lineSpacing":   "Interlineado",
        "reader.lineTight":     "Estrecho",
        "reader.lineNormal":    "Normal",
        "reader.lineWide":      "Amplio",
        "menu.app.about":       "Acerca de Jena Note",
        "menu.app.hide":        "Ocultar Jena Note",
        "menu.app.hideOthers":  "Ocultar otros",
        "menu.app.showAll":     "Mostrar todo",
        "menu.app.settings":    "Ajustes...",
        "menu.app.quit":        "Salir de Jena Note",
        "menu.file":            "Archivo",
        "menu.file.new":        "Nuevo documento",
        "menu.file.open":       "Abrir...",
        "menu.file.recent":     "Abrir recientes",
        "menu.file.recent.empty":"Sin elementos recientes",
        "menu.file.recent.clear":"Borrar lista",
        "menu.file.save":       "Guardar",
        "menu.file.saveAs":     "Guardar como...",
        "menu.file.export":     "Exportar...",
        "menu.file.export.docx":"Documento de Word (.docx)",
        "menu.file.export.hwpx":"Documento de Hangul (.hwpx)",
        "export.error.title":   "Error al exportar",
        "export.error.message": "No se pudo guardar el archivo.",
        "export.warn.title":    "Algunas imágenes omitidas",
        "export.warn.imageSkipped": "No se pudieron exportar %d imagen(es) y se omitieron.",
        "menu.file.revert":     "Revertir",
        "menu.file.close":      "Cerrar",
        "menu.edit":            "Edición",
        "menu.edit.undo":       "Deshacer",
        "menu.edit.redo":       "Rehacer",
        "menu.edit.cut":        "Cortar",
        "menu.edit.copy":       "Copiar",
        "menu.edit.paste":      "Pegar",
        "menu.edit.pastePlain":  "Pegar con el estilo del destino",
        "menu.edit.selectAll":  "Seleccionar todo",
        "menu.edit.find":       "Buscar...",
        "menu.format":          "Formato",
        "menu.format.bold":     "Negrita",
        "menu.format.italic":   "Cursiva",
        "menu.format.code":     "Código",
        "menu.format.h1":       "Título 1",
        "menu.format.h2":       "Título 2",
        "menu.format.h3":       "Título 3",
        "menu.format.body":     "Cuerpo",
        "menu.format.ul":       "Lista con viñetas",
        "menu.format.ol":       "Lista numerada",
        "menu.format.quote":    "Cita",
        "menu.format.link":     "Insertar enlace",
        "menu.window":          "Ventana",
        "menu.window.minimize": "Minimizar",
        "menu.window.zoom":     "Zoom",
        "menu.window.front":    "Traer todo al frente",
        "menu.help":            "Ayuda",
        "menu.help.help":       "Ayuda de Jena Note",
        "settings.title":       "Ajustes",
        "settings.language":    "Idioma",
        "settings.appearance":  "Modo de color",
        "appearance.system":    "Sistema",
        "appearance.light":     "Claro",
        "appearance.dark":      "Oscuro",
        "toolbar.bold":         "Negrita",
        "toolbar.italic":       "Cursiva",
        "toolbar.code":         "Código",
        "toolbar.h1":           "H1",
        "toolbar.h2":           "H2",
        "toolbar.h3":           "H3",
        "toolbar.body":         "Cuerpo",
        "toolbar.ul":           "Lista",
        "toolbar.ol":           "Numerada",
        "toolbar.quote":        "Cita",
        "toolbar.link":         "Enlace",
        "toolbar.hr":           "Separador",
        "toolbar.lineSpacing":  "Interlineado",
        "untitled":             "Sin título",
        "link.title":           "Insertar enlace",
        "link.message":         "Introduzca la URL",
        "link.insert":          "Insertar",
        "link.cancel":          "Cancelar",
        "help.title":           "Ayuda de Jena Note",
        "help.intro":           "Jena Note es un editor Markdown para macOS. Edita con formato visual — sin símbolos Markdown visibles — y guarda como archivos .md estándar CommonMark.",
        "help.file":            "Gestión de archivos",
        "help.file.new":        "Nuevo documento",
        "help.file.new.d":      "Archivo > Nuevo documento (⌘N) — Abre un documento en blanco en una nueva ventana.",
        "help.file.open":       "Abrir archivo",
        "help.file.open.d":     "Archivo > Abrir (⌘O) — Selecciona y abre un archivo .md.",
        "help.file.save":       "Guardar",
        "help.file.save.d":     "Archivo > Guardar (⌘S) — Guarda el documento actual.",
        "help.file.saveAs":     "Guardar como",
        "help.file.saveAs.d":   "Archivo > Guardar como (⇧⌘S) — Guarda con un nuevo nombre de archivo.",
        "help.file.recent":     "Documentos recientes",
        "help.file.recent.d":   "Archivo > Abrir recientes — Muestra los archivos abiertos recientemente. El más reciente se restaura al relanzar.",
        "help.format":          "Formato de texto",
        "help.format.intro":    "Selecciona texto y usa los botones de la barra de herramientas o atajos de teclado para aplicar formato.",
        "help.format.inline":   "Formato en línea",
        "help.format.bold":     "Negrita",
        "help.format.italic":   "Cursiva",
        "help.format.code":     "Código en línea",
        "help.format.code.d":   "Usar botón de barra de herramientas (requiere selección de texto)",
        "help.format.link":     "Insertar enlace",
        "help.format.link.d":   "⌘K (requiere selección de texto)",
        "help.format.para":     "Formato de párrafo",
        "help.format.body":     "Cuerpo",
        "help.format.body.d":   "Formato > Cuerpo",
        "help.format.h1":       "Título 1",
        "help.format.h1.d":     "Formato > Título 1",
        "help.format.h2":       "Título 2",
        "help.format.h2.d":     "Formato > Título 2",
        "help.format.h3":       "Título 3",
        "help.format.h3.d":     "Formato > Título 3",
        "help.format.ul":       "Lista con viñetas",
        "help.format.ul.d":     "Formato > Lista con viñetas",
        "help.format.ol":       "Lista numerada",
        "help.format.ol.d":     "Formato > Lista numerada",
        "help.format.quote":    "Cita",
        "help.format.quote.d":  "Formato > Cita",
        "help.format.hr":       "Línea horizontal",
        "help.format.hr.d":     "Formato > Separador o botón ─ de la barra de herramientas",
        "help.spacing":         "Interlineado",
        "help.spacing.d":       "Usa el control segmentado 1× · 1.5× · 2× en el lado derecho de la barra de herramientas para ajustar el interlineado.",
        "help.edit":            "Edición",
        "help.edit.undo":       "Deshacer",
        "help.edit.redo":       "Rehacer",
        "help.edit.cut":        "Cortar",
        "help.edit.copy":       "Copiar",
        "help.edit.paste":      "Pegar",
        "help.edit.pastePlain":  "Pegar con el estilo del destino",
        "help.edit.selectAll":  "Seleccionar todo",
        "help.edit.find":       "Buscar",
        "help.fileFormat":      "Formato de archivo",
        "help.fileFormat.d":    "Jena Note lee y escribe formato CommonMark (.md) con codificación UTF-8. Los archivos guardados son compatibles con todos los editores y visores Markdown estándar.",
    ]

    private static let de: [String: String] = [
        // View Menu (reader)
        "menu.view.readingMode":"Lesemodus",
        // Reader toolbar
        "reader.exit":          "Bearbeiten",
        "reader.pageMode":      "Seitenmodus",
        "reader.scroll":        "Scrollen",
        "reader.paged":         "Seiten",
        "reader.width":         "Breite",
        "reader.widthMobile":   "Mobil",
        "reader.widthBook":     "Buch",
        "reader.fontDown":      "Kleiner",
        "reader.fontUp":        "Größer",
        "reader.font":          "Schrift",
        "status.charCount":     "%@ Zeichen · %@ mit Leerzeichen",
        "reader.serif":         "Serif",
        "reader.sans":          "Sans",
        "reader.lineSpacing":   "Zeilenabstand",
        "reader.lineTight":     "Eng",
        "reader.lineNormal":    "Normal",
        "reader.lineWide":      "Weit",
        "menu.app.about":       "Über Jena Note",
        "menu.app.hide":        "Jena Note ausblenden",
        "menu.app.hideOthers":  "Andere ausblenden",
        "menu.app.showAll":     "Alle einblenden",
        "menu.app.settings":    "Einstellungen...",
        "menu.app.quit":        "Jena Note beenden",
        "menu.file":            "Ablage",
        "menu.file.new":        "Neues Dokument",
        "menu.file.open":       "Öffnen...",
        "menu.file.recent":     "Zuletzt benutzte Dokumente",
        "menu.file.recent.empty":"Keine letzten Objekte",
        "menu.file.recent.clear":"Liste löschen",
        "menu.file.save":       "Sichern",
        "menu.file.saveAs":     "Sichern unter...",
        "menu.file.export":     "Exportieren...",
        "menu.file.export.docx":"Word-Dokument (.docx)",
        "menu.file.export.hwpx":"Hangul-Dokument (.hwpx)",
        "export.error.title":   "Export fehlgeschlagen",
        "export.error.message": "Die Datei konnte nicht gespeichert werden.",
        "export.warn.title":    "Einige Bilder übersprungen",
        "export.warn.imageSkipped": "%d Bild(er) konnten nicht exportiert werden und wurden übersprungen.",
        "menu.file.revert":     "Zurücksetzen",
        "menu.file.close":      "Schließen",
        "menu.edit":            "Bearbeiten",
        "menu.edit.undo":       "Widerrufen",
        "menu.edit.redo":       "Wiederholen",
        "menu.edit.cut":        "Ausschneiden",
        "menu.edit.copy":       "Kopieren",
        "menu.edit.paste":      "Einsetzen",
        "menu.edit.pastePlain":  "Einsetzen und Stil anpassen",
        "menu.edit.selectAll":  "Alles auswählen",
        "menu.edit.find":       "Suchen...",
        "menu.format":          "Format",
        "menu.format.bold":     "Fett",
        "menu.format.italic":   "Kursiv",
        "menu.format.code":     "Code",
        "menu.format.h1":       "Überschrift 1",
        "menu.format.h2":       "Überschrift 2",
        "menu.format.h3":       "Überschrift 3",
        "menu.format.body":     "Fließtext",
        "menu.format.ul":       "Aufzählung",
        "menu.format.ol":       "Nummerierte Liste",
        "menu.format.quote":    "Zitat",
        "menu.format.link":     "Link einfügen",
        "menu.window":          "Fenster",
        "menu.window.minimize": "Im Dock ablegen",
        "menu.window.zoom":     "Zoomen",
        "menu.window.front":    "Alle nach vorne bringen",
        "menu.help":            "Hilfe",
        "menu.help.help":       "Jena Note Hilfe",
        "settings.title":       "Einstellungen",
        "settings.language":    "Sprache",
        "settings.appearance":  "Farbmodus",
        "appearance.system":    "System",
        "appearance.light":     "Hell",
        "appearance.dark":      "Dunkel",
        "toolbar.bold":         "Fett",
        "toolbar.italic":       "Kursiv",
        "toolbar.code":         "Code",
        "toolbar.h1":           "H1",
        "toolbar.h2":           "H2",
        "toolbar.h3":           "H3",
        "toolbar.body":         "Text",
        "toolbar.ul":           "Liste",
        "toolbar.ol":           "Nummeriert",
        "toolbar.quote":        "Zitat",
        "toolbar.link":         "Link",
        "toolbar.hr":           "Trennlinie",
        "toolbar.lineSpacing":  "Zeilenabstand",
        "untitled":             "Ohne Titel",
        "link.title":           "Link einfügen",
        "link.message":         "URL eingeben",
        "link.insert":          "Einfügen",
        "link.cancel":          "Abbrechen",
        "help.title":           "Jena Note Hilfe",
        "help.intro":           "Jena Note ist ein Markdown-Editor für macOS. Bearbeiten Sie Texte mit sichtbarer Formatierung — ohne Markdown-Symbole — und speichern Sie als Standard-CommonMark-.md-Dateien.",
        "help.file":            "Dateiverwaltung",
        "help.file.new":        "Neues Dokument",
        "help.file.new.d":      "Ablage > Neues Dokument (⌘N) — Öffnet ein leeres Dokument in einem neuen Fenster.",
        "help.file.open":       "Datei öffnen",
        "help.file.open.d":     "Ablage > Öffnen (⌘O) — Wählen und öffnen Sie eine .md-Datei.",
        "help.file.save":       "Sichern",
        "help.file.save.d":     "Ablage > Sichern (⌘S) — Speichert das aktuelle Dokument.",
        "help.file.saveAs":     "Sichern unter",
        "help.file.saveAs.d":   "Ablage > Sichern unter (⇧⌘S) — Speichert unter einem neuen Dateinamen.",
        "help.file.recent":     "Zuletzt benutzte Dokumente",
        "help.file.recent.d":   "Ablage > Zuletzt benutzte Dokumente — Zeigt die zuletzt geöffneten Dateien. Die letzte Datei wird beim Neustart wiederhergestellt.",
        "help.format":          "Textformatierung",
        "help.format.intro":    "Wählen Sie Text aus und verwenden Sie Symbolleisten-Schaltflächen oder Tastenkombinationen, um Formatierungen anzuwenden.",
        "help.format.inline":   "Inline-Formatierung",
        "help.format.bold":     "Fett",
        "help.format.italic":   "Kursiv",
        "help.format.code":     "Inline-Code",
        "help.format.code.d":   "Symbolleisten-Schaltfläche verwenden (Textauswahl erforderlich)",
        "help.format.link":     "Link einfügen",
        "help.format.link.d":   "⌘K (Textauswahl erforderlich)",
        "help.format.para":     "Absatzformatierung",
        "help.format.body":     "Fließtext",
        "help.format.body.d":   "Format > Fließtext",
        "help.format.h1":       "Überschrift 1",
        "help.format.h1.d":     "Format > Überschrift 1",
        "help.format.h2":       "Überschrift 2",
        "help.format.h2.d":     "Format > Überschrift 2",
        "help.format.h3":       "Überschrift 3",
        "help.format.h3.d":     "Format > Überschrift 3",
        "help.format.ul":       "Aufzählung",
        "help.format.ul.d":     "Format > Aufzählung",
        "help.format.ol":       "Nummerierte Liste",
        "help.format.ol.d":     "Format > Nummerierte Liste",
        "help.format.quote":    "Zitat",
        "help.format.quote.d":  "Format > Zitat",
        "help.format.hr":       "Horizontale Linie",
        "help.format.hr.d":     "Format > Trennlinie oder Symbolleisten-Schaltfläche ─",
        "help.spacing":         "Zeilenabstand",
        "help.spacing.d":       "Verwenden Sie das Segmentsteuerung 1× · 1.5× · 2× auf der rechten Seite der Symbolleiste, um den Zeilenabstand anzupassen.",
        "help.edit":            "Bearbeiten",
        "help.edit.undo":       "Widerrufen",
        "help.edit.redo":       "Wiederholen",
        "help.edit.cut":        "Ausschneiden",
        "help.edit.copy":       "Kopieren",
        "help.edit.paste":      "Einsetzen",
        "help.edit.pastePlain":  "Einsetzen und Stil anpassen",
        "help.edit.selectAll":  "Alles auswählen",
        "help.edit.find":       "Suchen",
        "help.fileFormat":      "Dateiformat",
        "help.fileFormat.d":    "Jena Note liest und schreibt CommonMark-Format (.md) mit UTF-8-Kodierung. Gespeicherte Dateien sind mit allen Standard-Markdown-Editoren und -Viewern kompatibel.",
    ]

    private static let fr: [String: String] = [
        // View Menu (reader)
        "menu.view.readingMode":"Mode lecture",
        // Reader toolbar
        "reader.exit":          "Éditer",
        "reader.pageMode":      "Mode page",
        "reader.scroll":        "Défilement",
        "reader.paged":         "Pages",
        "reader.width":         "Largeur",
        "reader.widthMobile":   "Mobile",
        "reader.widthBook":     "Livre",
        "reader.fontDown":      "Réduire",
        "reader.fontUp":        "Agrandir",
        "reader.font":          "Police",
        "status.charCount":     "%@ caractères · %@ avec espaces",
        "reader.serif":         "Serif",
        "reader.sans":          "Sans",
        "reader.lineSpacing":   "Interligne",
        "reader.lineTight":     "Serré",
        "reader.lineNormal":    "Normal",
        "reader.lineWide":      "Large",
        "menu.app.about":       "À propos de Jena Note",
        "menu.app.hide":        "Masquer Jena Note",
        "menu.app.hideOthers":  "Masquer les autres",
        "menu.app.showAll":     "Tout afficher",
        "menu.app.settings":    "Réglages...",
        "menu.app.quit":        "Quitter Jena Note",
        "menu.file":            "Fichier",
        "menu.file.new":        "Nouveau document",
        "menu.file.open":       "Ouvrir...",
        "menu.file.recent":     "Ouvrir les éléments récents",
        "menu.file.recent.empty":"Aucun élément récent",
        "menu.file.recent.clear":"Effacer la liste",
        "menu.file.save":       "Enregistrer",
        "menu.file.saveAs":     "Enregistrer sous...",
        "menu.file.export":     "Exporter...",
        "menu.file.export.docx":"Document Word (.docx)",
        "menu.file.export.hwpx":"Document Hangul (.hwpx)",
        "export.error.title":   "Échec de l'exportation",
        "export.error.message": "Impossible d'enregistrer le fichier.",
        "export.warn.title":    "Certaines images ignorées",
        "export.warn.imageSkipped": "%d image(s) n'ont pas pu être exportées et ont été ignorées.",
        "menu.file.revert":     "Revenir à la version enregistrée",
        "menu.file.close":      "Fermer",
        "menu.edit":            "Édition",
        "menu.edit.undo":       "Annuler",
        "menu.edit.redo":       "Rétablir",
        "menu.edit.cut":        "Couper",
        "menu.edit.copy":       "Copier",
        "menu.edit.paste":      "Coller",
        "menu.edit.pastePlain":  "Coller et adapter le style",
        "menu.edit.selectAll":  "Tout sélectionner",
        "menu.edit.find":       "Rechercher...",
        "menu.format":          "Format",
        "menu.format.bold":     "Gras",
        "menu.format.italic":   "Italique",
        "menu.format.code":     "Code",
        "menu.format.h1":       "Titre 1",
        "menu.format.h2":       "Titre 2",
        "menu.format.h3":       "Titre 3",
        "menu.format.body":     "Corps",
        "menu.format.ul":       "Liste à puces",
        "menu.format.ol":       "Liste numérotée",
        "menu.format.quote":    "Citation",
        "menu.format.link":     "Insérer un lien",
        "menu.window":          "Fenêtre",
        "menu.window.minimize": "Réduire",
        "menu.window.zoom":     "Agrandir",
        "menu.window.front":    "Tout ramener au premier plan",
        "menu.help":            "Aide",
        "menu.help.help":       "Aide Jena Note",
        "settings.title":       "Réglages",
        "settings.language":    "Langue",
        "settings.appearance":  "Mode couleur",
        "appearance.system":    "Système",
        "appearance.light":     "Clair",
        "appearance.dark":      "Sombre",
        "toolbar.bold":         "Gras",
        "toolbar.italic":       "Italique",
        "toolbar.code":         "Code",
        "toolbar.h1":           "H1",
        "toolbar.h2":           "H2",
        "toolbar.h3":           "H3",
        "toolbar.body":         "Corps",
        "toolbar.ul":           "Liste",
        "toolbar.ol":           "Numérotée",
        "toolbar.quote":        "Citation",
        "toolbar.link":         "Lien",
        "toolbar.hr":           "Séparateur",
        "toolbar.lineSpacing":  "Interligne",
        "untitled":             "Sans titre",
        "link.title":           "Insérer un lien",
        "link.message":         "Entrez l'URL",
        "link.insert":          "Insérer",
        "link.cancel":          "Annuler",
        "help.title":           "Aide Jena Note",
        "help.intro":           "Jena Note est un éditeur Markdown pour macOS. Modifiez avec un formatage visuel — sans symboles Markdown visibles — et enregistrez en fichiers .md CommonMark standard.",
        "help.file":            "Gestion des fichiers",
        "help.file.new":        "Nouveau document",
        "help.file.new.d":      "Fichier > Nouveau document (⌘N) — Ouvre un document vierge dans une nouvelle fenêtre.",
        "help.file.open":       "Ouvrir un fichier",
        "help.file.open.d":     "Fichier > Ouvrir (⌘O) — Sélectionnez et ouvrez un fichier .md.",
        "help.file.save":       "Enregistrer",
        "help.file.save.d":     "Fichier > Enregistrer (⌘S) — Enregistre le document actuel.",
        "help.file.saveAs":     "Enregistrer sous",
        "help.file.saveAs.d":   "Fichier > Enregistrer sous (⇧⌘S) — Enregistre avec un nouveau nom de fichier.",
        "help.file.recent":     "Documents récents",
        "help.file.recent.d":   "Fichier > Ouvrir les éléments récents — Affiche les fichiers récemment ouverts. Le plus récent est restauré au relancement.",
        "help.format":          "Mise en forme du texte",
        "help.format.intro":    "Sélectionnez du texte, puis utilisez les boutons de la barre d'outils ou les raccourcis clavier pour appliquer la mise en forme.",
        "help.format.inline":   "Mise en forme en ligne",
        "help.format.bold":     "Gras",
        "help.format.italic":   "Italique",
        "help.format.code":     "Code en ligne",
        "help.format.code.d":   "Utilisez le bouton de la barre d'outils (sélection de texte requise)",
        "help.format.link":     "Insérer un lien",
        "help.format.link.d":   "⌘K (sélection de texte requise)",
        "help.format.para":     "Mise en forme des paragraphes",
        "help.format.body":     "Corps",
        "help.format.body.d":   "Format > Corps",
        "help.format.h1":       "Titre 1",
        "help.format.h1.d":     "Format > Titre 1",
        "help.format.h2":       "Titre 2",
        "help.format.h2.d":     "Format > Titre 2",
        "help.format.h3":       "Titre 3",
        "help.format.h3.d":     "Format > Titre 3",
        "help.format.ul":       "Liste à puces",
        "help.format.ul.d":     "Format > Liste à puces",
        "help.format.ol":       "Liste numérotée",
        "help.format.ol.d":     "Format > Liste numérotée",
        "help.format.quote":    "Citation",
        "help.format.quote.d":  "Format > Citation",
        "help.format.hr":       "Ligne horizontale",
        "help.format.hr.d":     "Format > Séparateur ou bouton ─ de la barre d'outils",
        "help.spacing":         "Interligne",
        "help.spacing.d":       "Utilisez le contrôle segmenté 1× · 1.5× · 2× à droite de la barre d'outils pour ajuster l'interligne.",
        "help.edit":            "Édition",
        "help.edit.undo":       "Annuler",
        "help.edit.redo":       "Rétablir",
        "help.edit.cut":        "Couper",
        "help.edit.copy":       "Copier",
        "help.edit.paste":      "Coller",
        "help.edit.pastePlain":  "Coller et adapter le style",
        "help.edit.selectAll":  "Tout sélectionner",
        "help.edit.find":       "Rechercher",
        "help.fileFormat":      "Format de fichier",
        "help.fileFormat.d":    "Jena Note lit et écrit le format CommonMark (.md) avec encodage UTF-8. Les fichiers enregistrés sont compatibles avec tous les éditeurs et lecteurs Markdown standard.",
    ]
}
